language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 6.1
  - 6.0
  - 5.11

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  email: kazuhtan0815@yahoo.co.jp
